/**
 * OpenAPI documentation.
 *
 * The document is *not* inferred from the routes Fastify happens to have. It
 * is generated by `buildOpenApiDocument()` from the same descriptors the
 * routes are registered with, and served verbatim. That is the whole point:
 * the published contract and the enforced contract are one artefact, so they
 * cannot disagree.
 *
 * @module @desi-event/api/plugins/docs
 */

import swagger from '@fastify/swagger'
import swaggerUi from '@fastify/swagger-ui'
import { buildOpenApiDocument } from '@desi-event/api-contract'

/** Where the interactive documentation is mounted. */
export const DOCS_ROUTE_PREFIX = '/docs'

/** Where the raw document is served. */
export const OPENAPI_ROUTE = '/openapi.json'

/**
 * Build the OpenAPI document for a running instance.
 *
 * @param {object} [options] Document options.
 * @param {string} [options.version] Version string reported in `info.version`.
 * @param {Array<{url: string, description?: string}>} [options.servers] Servers to advertise.
 * @returns {object} An OpenAPI 3.1 document.
 */
export function buildDocument(options = {}) {
  const { version = '1.0.0', servers } = options

  return buildOpenApiDocument({
    title: 'Desi-Event API',
    version,
    ...(servers ? { servers } : {}),
  })
}

/**
 * Register Swagger and Swagger UI.
 *
 * @param {object} app The Fastify instance.
 * @param {object} [options] Documentation options.
 * @param {string} [options.version] Version reported in the document.
 * @param {Array<{url: string, description?: string}>} [options.servers] Servers to advertise.
 * @returns {Promise<object>} The document that was registered.
 */
export async function registerDocs(app, options = {}) {
  const document = buildDocument(options)

  await app.register(swagger, { mode: 'static', specification: { document } })

  await app.register(swaggerUi, {
    routePrefix: DOCS_ROUTE_PREFIX,
    staticCSP: true,
    uiConfig: { docExpansion: 'list', deepLinking: true },
  })

  app.get(OPENAPI_ROUTE, { schema: {} }, async () => document)

  return document
}
