/**
 * Leaf schemas every other schema in this package is built from.
 *
 * Two conventions run through the file:
 *
 *  * **Normalisation happens in `z.preprocess`, never in `.transform()`.**
 *    `@desi-event/api-contract` renders these schemas to JSON Schema with
 *    `z.toJSONSchema`, and a trailing transform is not representable. A
 *    preprocess step keeps the *output* type a plain string, so the generated
 *    OpenAPI document stays accurate.
 *  * **Money is integer cents.** There is no float money schema here on
 *    purpose.
 *
 * @module @desi-event/schemas/primitives
 */

import { z } from 'zod'

/** Longest identifier accepted anywhere in the system. */
export const MAX_ID_LENGTH = 64

/** Upper bound for any cents value: ten million major units. */
export const MAX_CENTS = 1_000_000_000

/** Default page number used when a list query omits `page`. */
export const DEFAULT_PAGE = 1

/** Default page size used when a list query omits `perPage`. */
export const DEFAULT_PER_PAGE = 20

/** Hard cap on page size, so a single request cannot drain a table. */
export const MAX_PER_PAGE = 100

/** Hard cap on page number, which bounds the offset a query can produce. */
export const MAX_PAGE = 10_000

/**
 * Trim a string, leaving every other value untouched so that the wrapped
 * schema still reports a proper `invalid_type` issue.
 *
 * @param {unknown} value Raw input.
 * @returns {unknown} Trimmed string, or `value` unchanged.
 */
function trimmed(value) {
  return typeof value === 'string' ? value.trim() : value
}

/**
 * Trim and lower-case a string, leaving non-strings untouched.
 *
 * @param {unknown} value Raw input.
 * @returns {unknown} Normalised string, or `value` unchanged.
 */
function trimmedLower(value) {
  return typeof value === 'string' ? value.trim().toLowerCase() : value
}

/**
 * Trim and upper-case a string, leaving non-strings untouched.
 *
 * @param {unknown} value Raw input.
 * @returns {unknown} Normalised string, or `value` unchanged.
 */
function trimmedUpper(value) {
  return typeof value === 'string' ? value.trim().toUpperCase() : value
}

/**
 * True when the runtime recognises `value` as an IANA time zone name.
 *
 * @param {string} value Candidate zone name, e.g. `Asia/Kolkata`.
 * @returns {boolean} Whether `Intl` accepts the zone.
 */
function isKnownTimeZone(value) {
  try {
    new Intl.DateTimeFormat('en-US', { timeZone: value })
    return true
  } catch {
    return false
  }
}

const DATE_ONLY = /^\d{4}-\d{2}-\d{2}$/
const OFFSETLESS_DATETIME = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2}(\.\d+)?)?$/

/**
 * Accept the several shapes a timestamp arrives in and normalise them to a
 * UTC ISO-8601 string.
 *
 * Prisma hands back `Date` objects, JSON bodies carry strings, and query
 * strings frequently carry a bare `YYYY-MM-DD`. All three mean the same thing
 * to a caller, so all three are accepted and an offsetless value is read as
 * UTC rather than as the server's local zone.
 *
 * @param {unknown} value Raw input.
 * @returns {unknown} An ISO-8601 string, or `value` unchanged.
 */
function toIsoString(value) {
  if (value instanceof Date) {
    return Number.isNaN(value.getTime()) ? 'Invalid Date' : value.toISOString()
  }
  if (typeof value !== 'string') return value

  const text = value.trim()
  if (DATE_ONLY.test(text)) return `${text}T00:00:00.000Z`
  if (OFFSETLESS_DATETIME.test(text)) return `${text.length === 16 ? `${text}:00` : text}Z`
  return text
}

/** A CUID/CUID2 primary key as generated by Prisma's `@default(cuid())`. */
export const cuidSchema = z.preprocess(
  trimmed,
  z
    .string()
    .max(MAX_ID_LENGTH)
    .regex(/^[a-z][a-z0-9]{7,31}$/, 'Expected a CUID identifier'),
)

/** A trimmed, lower-cased email address. */
export const emailSchema = z.preprocess(trimmedLower, z.email().max(254))

/** A URL-safe slug: lower-case words joined by single hyphens. */
export const slugSchema = z.preprocess(
  trimmedLower,
  z
    .string()
    .min(1)
    .max(140)
    .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'Expected a lower-case hyphenated slug'),
)

/** An ISO-4217 currency code, upper-cased on the way in. */
export const currencySchema = z.preprocess(
  trimmedUpper,
  z.string().regex(/^[A-Z]{3}$/, 'Expected a three-letter ISO-4217 currency code'),
)

/** A money amount in the smallest currency unit. Never negative, never a float. */
export const centsSchema = z.int().min(0).max(MAX_CENTS)

/** A signed money amount, for adjustments that may reduce a total. */
export const signedCentsSchema = z.int().min(-MAX_CENTS).max(MAX_CENTS)

/** Basis points: 1 bp = 0.01%, so 10000 bps is 100%. */
export const bpsSchema = z.int().min(0).max(10_000)

/** A strict ISO-8601 datetime string carrying `Z` or an explicit offset. */
export const isoDateTimeSchema = z.iso.datetime({ offset: true })

/**
 * A timestamp that also accepts a `Date` (as Prisma returns) or a bare
 * `YYYY-MM-DD`, and always parses to a UTC ISO-8601 string.
 */
export const timestampSchema = z.preprocess(toIsoString, isoDateTimeSchema)

/** Alias kept for query parameters, where the date-only form is common. */
export const queryDateTimeSchema = timestampSchema

/** An IANA time zone identifier the runtime actually knows about. */
export const timezoneSchema = z.preprocess(
  trimmed,
  z.string().min(1).max(64).refine(isKnownTimeZone, 'Unknown IANA time zone'),
)

/** An absolute `http(s)` URL. */
export const urlSchema = z.preprocess(
  trimmed,
  z
    .url()
    .max(2048)
    .refine((value) => /^https?:\/\//i.test(value), 'Expected an http or https URL'),
)

/** Any non-empty trimmed string, capped so a body cannot carry a novel. */
export const nonEmptyStringSchema = z.preprocess(trimmed, z.string().min(1).max(500))

/** Free-form long text such as an event description. */
export const richTextSchema = z.preprocess(trimmed, z.string().min(1).max(20_000))

/** A loose international phone number; formatting is left to the caller. */
export const phoneSchema = z.preprocess(
  trimmed,
  z
    .string()
    .min(6)
    .max(24)
    .regex(/^\+?[0-9][0-9 ()-]{4,}$/, 'Expected a phone number'),
)

/** A BCP-47 locale tag such as `en-IN`. */
export const localeSchema = z.preprocess(
  trimmed,
  z.string().regex(/^[a-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$/, 'Expected a BCP-47 locale tag'),
)

/** An ISO-3166-1 alpha-2 country code. */
export const countrySchema = z.preprocess(
  trimmedUpper,
  z.string().regex(/^[A-Z]{2}$/, 'Expected a two-letter ISO-3166 country code'),
)

/** Latitude in decimal degrees. */
export const latitudeSchema = z.number().min(-90).max(90)

/** Longitude in decimal degrees. */
export const longitudeSchema = z.number().min(-180).max(180)

/** A password at registration time. Length is the only rule enforced here. */
export const passwordSchema = z.string().min(8).max(128)

/** The opaque code printed on a ticket and encoded into its QR pass. */
export const ticketCodeSchema = z.preprocess(
  trimmedUpper,
  z
    .string()
    .min(6)
    .max(64)
    .regex(/^[A-Z0-9-]+$/, 'Expected an alphanumeric ticket code'),
)

/** A human-typed promotional code. Case is normalised so `save10` == `SAVE10`. */
export const promoCodeStringSchema = z.preprocess(
  trimmedUpper,
  z
    .string()
    .min(3)
    .max(32)
    .regex(/^[A-Z0-9_-]+$/, 'Expected an alphanumeric promo code'),
)

/** The customer-facing order reference, e.g. `DE-8F3K2Q`. */
export const orderReferenceSchema = z.preprocess(
  trimmedUpper,
  z
    .string()
    .min(4)
    .max(32)
    .regex(/^[A-Z0-9-]+$/, 'Expected an alphanumeric order reference'),
)

/** A ticket quantity on a single order line. */
export const quantitySchema = z.int().min(1).max(50)

/** A non-negative inventory count. */
export const countSchema = z.int().min(0).max(10_000_000)

/** `page` query parameter: coerced from the string a URL carries. */
export const pageSchema = z.coerce.number().int().min(1).max(MAX_PAGE).default(DEFAULT_PAGE)

/** `perPage` query parameter, capped at {@link MAX_PER_PAGE}. */
export const perPageSchema = z.coerce
  .number()
  .int()
  .min(1)
  .max(MAX_PER_PAGE)
  .default(DEFAULT_PER_PAGE)

/** Page/perPage pair shared by every list endpoint. */
export const paginationQuerySchema = z.object({
  page: pageSchema,
  perPage: perPageSchema,
})

/**
 * Translate a parsed pagination query into Prisma `skip`/`take` arguments.
 *
 * @param {{page?: number, perPage?: number}} [pagination] A parsed pagination query.
 * @returns {{skip: number, take: number}} Offset arguments for Prisma.
 */
export function toSkipTake(pagination = {}) {
  const page = pagination.page ?? DEFAULT_PAGE
  const perPage = pagination.perPage ?? DEFAULT_PER_PAGE
  return { skip: (page - 1) * perPage, take: perPage }
}
