var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/events/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__06nq2_0._.js")
R.c("server/chunks/ssr/0-cz_next_dist_0x2p7ro._.js")
R.c("server/chunks/ssr/06bi_zod_v4_classic_1llnmub._.js")
R.c("server/chunks/ssr/06bi_zod_v4_core_1a0cqp_._.js")
R.c("server/chunks/ssr/06bi_zod_v4_locales_1-4d6w5._.js")
R.c("server/chunks/ssr/0-cz_next_dist_esm_server_00d-kx1._.js")
R.c("server/chunks/ssr/0-cz_next_dist_esm_lib_1ll-8dv._.js")
R.c("server/chunks/ssr/0-cz_next_dist_esm_0d_vd4b._.js")
R.c("server/chunks/ssr/0-cz_next_dist_compiled_0mdbxw9._.js")
R.c("server/chunks/ssr/0-cz_next_dist_server_route-modules_app-page_0qf80d3._.js")
R.c("server/chunks/ssr/[externals]__05yr04l._.js")
R.c("server/chunks/ssr/_1mh7mgm._.js")
R.c("server/chunks/ssr/apps_web_src_app_error_jsx_1gap19f._.js")
R.c("server/chunks/ssr/apps_web_src_1e-697o._.js")
R.c("server/chunks/ssr/0-cz_next_dist_client_components_0qvq823._.js")
R.c("server/chunks/ssr/0-cz_next_dist_client_components_builtin_unauthorized_1ic6iay.js")
R.c("server/chunks/ssr/apps_web_src_app_global-error_jsx_1hrg-sa._.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_events_[slug]_page_actions_0vwfs_h.js")
R.m("[project]/node_modules/.pnpm/next@16.3.5_@playwright+test@1.63.0_@types+node@26.5.1_react-dom@19.3.0_react@19.3.0__react@19.3.0/node_modules/next/dist/esm/build/templates/app-page.js?page=/events/[slug]/page { MODULE_0 => \"[project]/apps/web/src/app/layout.jsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/apps/web/src/app/error.jsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/apps/web/src/app/not-found.jsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/.pnpm/next@16.3.5_@playwright+test@1.63.0_@types+node@26.5.1_react-dom@19.3.0_react@19.3.0__react@19.3.0/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/.pnpm/next@16.3.5_@playwright+test@1.63.0_@types+node@26.5.1_react-dom@19.3.0_react@19.3.0__react@19.3.0/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/apps/web/src/app/global-error.jsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/apps/web/src/app/events/[slug]/page.jsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/node_modules/.pnpm/next@16.3.5_@playwright+test@1.63.0_@types+node@26.5.1_react-dom@19.3.0_react@19.3.0__react@19.3.0/node_modules/next/dist/esm/build/templates/app-page.js?page=/events/[slug]/page { MODULE_0 => \"[project]/apps/web/src/app/layout.jsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/apps/web/src/app/error.jsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/apps/web/src/app/not-found.jsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/.pnpm/next@16.3.5_@playwright+test@1.63.0_@types+node@26.5.1_react-dom@19.3.0_react@19.3.0__react@19.3.0/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/.pnpm/next@16.3.5_@playwright+test@1.63.0_@types+node@26.5.1_react-dom@19.3.0_react@19.3.0__react@19.3.0/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/apps/web/src/app/global-error.jsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/apps/web/src/app/events/[slug]/page.jsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
