var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/events/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0byubk0._.js")
R.c("server/chunks/ssr/apps_web_src_lib_pricing_1lakh7i.js")
R.c("server/chunks/ssr/apps_web_src_1f3g469._.js")
R.c("server/chunks/ssr/0-cz_next_dist_1q-cai9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1-7kkyw._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1c9ol59._.js")
R.c("server/chunks/ssr/_215z1md._.js")
R.c("server/chunks/ssr/apps_web_src_app_error_jsx_10biaou._.js")
R.c("server/chunks/ssr/apps_web_src_1e-697o._.js")
R.c("server/chunks/ssr/0-cz_next_dist_client_components_0qvq823._.js")
R.c("server/chunks/ssr/0-cz_next_dist_client_components_builtin_unauthorized_1ic6iay.js")
R.c("server/chunks/ssr/apps_web_src_app_global-error_jsx_1lyli3k._.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_events_page_actions_077653b.js")
R.m(9339)
module.exports=R.m(9339).exports
